### ISSUE TITLE
Is this project still being maintained? Stuck on "Reading playlists from iTunes"

### ISSUE THREAD

**Issue by leninsaccountant** [vbtrek/PlexRatingsSync#7]
I have set everything up in the options perfectly, but when I exit back to the main screen, "Reading playlists from iTunes" just stays there.

Thanks!

**Comment by leninsaccountant** [comment]
I can't find a way to contact you, but if you click on my Github profile and send me an email, I am willing to pay you for your time if you can get this back up and running.

**Comment by EarthBoundX5** [comment]
@leninsaccountant why did you close this?  I think @vbtrek was just attaching related requests to it.  I myself too am just crashing on startup with no discernible reason.

**Comment by mavproductions** [comment]
Really wish this project was reopened with plexamp becoming more and more used.
