### ISSUE TITLE
FLAC support?

### ISSUE THREAD

**Issue by leninsaccountant** [vbtrek/PlexRatingsSync#8]
This app works brilliantly for pushing my ratings to PleX. Pushing playlists doesn't work, but I guess that is a separate issue.

Would it be possible to add FLAC support? Many music players, such as Musicbee, include the option to output their database as an iTunes XML file. This is what I pointed PlexRatingsSync to, and it transferred the mp3s perfectly.

It didn't, however, transfer the FLACs. I know this is essentially because iTunes doesn't support FLAC, but it would be a really great feature to add!

If it helps, this is what a FLAC entry looks like in my iTunes XML:

<dict>
			<key>Track ID</key><integer>32626</integer>
			<key>Composer</key><string>Man At The Off Licence</string>
			<key>Comments</key><string>No surprises here, just the well-constructed, deviously quirky pop/rock that one came to expect from Cleaners from Venus. Everything here was written and played in a bedroom on an eight-track machine by &#34;the Psychedelic Gardener&#34; (i.e., Martin Newell). It&#39;s probably one of Cleaners&#39; most straightforward releases, but also one of their most accomplished, with a few songs that would be re-recorded for Newell&#39;s solo album, The Greatest Living Englishman.</string>
			<key>Encoder</key><string>reference libFLAC 1.2.1 20070917</string>
			<key>Genre1</key><string>Lo-Fi</string>
			<key>Genre2</key><string>Power Pop</string>
			<key>Genre3</key><string>Jangle Pop</string>
			<key>Genre4</key><string>Neo-Psychedelia</string>
			<key>Genre5</key><string>Slacker Rock</string>
			<key>Genre6</key><string>Post-Punk</string>
			<key>Disc Number</key><integer>1</integer>
			<key>Track Number</key><integer>1</integer>
			<key>Name</key><string>The Jangling Man</string>
			<key>Artist</key><string>The Cleaners From Venus</string>
			<key>Album Artist</key><string>The Cleaners From Venus</string>
			<key>Album</key><string>Number Thirteen</string>
			<key>Year</key><integer>1990</integer>
			<key>Genre</key><string>Lo-Fi</string>
			<key>Rating</key><integer>90</integer>
			<key>Kind</key><string>FLAC audio file</string>
			<key>Size</key><integer>33825306</integer>
			<key>Total Time</key><integer>289826</integer>
			<key>Date Modified</key><date>2022-01-15T20:48:00Z</date>
			<key>Date Added</key><date>2020-10-19T08:58:46Z</date>
			<key>Bit Rate</key><integer>931</integer>
			<key>Sample Rate</key><integer>44100</integer>
			<key>Play Count</key><integer>2</integer>
			<key>Play Date UTC</key><date>2020-10-28T09:03:30Z</date>
			<key>Persistent ID</key><string>58C5BFD08E9F41ED</string>
			<key>Track Type</key><string>File</string>
			<key>Location</key><string>file://localhost/Z:/Musicbee/Music/The%20Cleaners%20From%20Venus/Number%20Thirteen/101%20-%20The%20Jangling%20Man.flac</string>
		</dict>

**Comment by leninsaccountant** [comment]
better formatting:

```
<dict>
			<key>Track ID</key><integer>32626</integer>
			<key>Composer</key><string>Man At The Off Licence</string>
			<key>Comments</key><string>No surprises here, just the well-constructed, deviously quirky pop/rock that one came to expect from Cleaners from Venus. Everything here was written and played in a bedroom on an eight-track machine by &#34;the Psychedelic Gardener&#34; (i.e., Martin Newell). It&#39;s probably one of Cleaners&#39; most straightforward releases, but also one of their most accomplished, with a few songs that would be re-recorded for Newell&#39;s solo album, The Greatest Living Englishman.</string>
			<key>Encoder</key><string>reference libFLAC 1.2.1 20070917</string>
			<key>Genre1</key><string>Lo-Fi</string>
			<key>Genre2</key><string>Power Pop</string>
			<key>Genre3</key><string>Jangle Pop</string>
			<key>Genre4</key><string>Neo-Psychedelia</string>
			<key>Genre5</key><string>Slacker Rock</string>
			<key>Genre6</key><string>Post-Punk</string>
			<key>Disc Number</key><integer>1</integer>
			<key>Track Number</key><integer>1</integer>
			<key>Name</key><string>The Jangling Man</string>
			<key>Artist</key><string>The Cleaners From Venus</string>
			<key>Album Artist</key><string>The Cleaners From Venus</string>
			<key>Album</key><string>Number Thirteen</string>
			<key>Year</key><integer>1990</integer>
			<key>Genre</key><string>Lo-Fi</string>
			<key>Rating</key><integer>90</integer>
			<key>Kind</key><string>FLAC audio file</string>
			<key>Size</key><integer>33825306</integer>
			<key>Total Time</key><integer>289826</integer>
			<key>Date Modified</key><date>2022-01-15T20:48:00Z</date>
			<key>Date Added</key><date>2020-10-19T08:58:46Z</date>
			<key>Bit Rate</key><integer>931</integer>
			<key>Sample Rate</key><integer>44100</integer>
			<key>Play Count</key><integer>2</integer>
			<key>Play Date UTC</key><date>2020-10-28T09:03:30Z</date>
			<key>Persistent ID</key><string>58C5BFD08E9F41ED</string>
			<key>Track Type</key><string>File</string>
			<key>Location</key><string>file://localhost/Z:/Musicbee/Music/The%20Cleaners%20From%20Venus/Number%20Thirteen/101%20-%20The%20Jangling%20Man.flac</string>
		</dict>
```

**Comment by vbtrek** [comment]
Hi, just so I'm clear on the requirement. You are managing your library in MusicBee, exporting an iTunes library file from MusicBee with FLAC files and ratings all within the iTunes library file, then you want to sync those ratings to Plex?

**Comment by leninsaccountant** [comment]
Yes! That's basically it.

Musicbee has a feature which allows it to export its library as an iTunes XML file called 'iTunes Music Library.xml'.

Inside this, there are a mixture of tracks which are .mp3 and .flac. 

I point your program to the XML file exported by MusicBee, and it syncs ratings great - but only for .mp3 files. 

That makes sense, because iTunes doesn't support FLAC files. But I am wondering if you could update the program to support the FLAC files contained in the XML file which MusicBee exports?

Thanks!

**Comment by vbtrek** [comment]
Ok, cool. I've been reacquainting myself with the code, and the current code sync's the ratings stored within the file attributes with Plex rather than the ratings in the iTunes library file. I can extend the settings to allow you to choose your preferred ratings source, I'll take a look when I get chance. Thanks

**Comment by vbtrek** [comment]
Sorry, I've not used this tool in many years and the project is going to be archived as it's no longer possible to read/update ratings from/to the plex dtabase.
